"""
Create backend/.env if it is missing.

Generates the two secrets that must be stable across restarts, and leaves
every optional integration unset — the app runs without them and says so on
/api/v1/health. Never overwrites an existing .env.
"""

import os
import secrets
import sys

BACKEND = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "backend")
ENV_PATH = os.path.join(BACKEND, ".env")

TEMPLATE = """# Generated by scripts/bootstrap_env.py — safe to edit.
# See .env.example for every available setting.

APP_ENV=development

# Must stay stable across restarts, or sessions and live OTPs are invalidated.
JWT_SECRET={jwt}
OTP_SECRET={otp}

# Passwordless local sign-in. Turn this off anywhere real.
ALLOW_DEV_SIGNIN=1

# No Shiprocket credentials, so the courier is simulated.
TRANSPORT_MODE=mock

DATABASE_URL=sqlite:///./plateletiq.db

# Add a LAN address here to run the two consoles on two machines.
ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174
"""


def main() -> int:
    if os.path.exists(ENV_PATH):
        print("backend/.env already exists — leaving it alone.")
        return 0

    os.makedirs(BACKEND, exist_ok=True)
    with open(ENV_PATH, "w", encoding="utf-8") as handle:
        handle.write(TEMPLATE.format(jwt=secrets.token_hex(32), otp=secrets.token_hex(32)))

    print("Created backend/.env with freshly generated secrets.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
